---
title: "How to contribute"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to contribute}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Contributions to `shi18ny` are very welcome and greatly appreciated! Every contribution helps to improve the quality
and reliability of the translations, and every contribution will be given credit.

There are many ways in which you can help us improve `shi18ny`:

# Ways to contribute

## Translations

### Add a new language

If the language you are looking for is not yet supported you can help by either
1. filing an issue on the `shi18ny` [GitHub page](https://github.com/datasketch/shi18ny), or
2. submitting your own translations to the package.

To create your own translations, follow these steps:

* Follow the steps in the `vignette("getting-started")` guide (under **To contribute**) to fork, clone and install the package.
* Locate the `ui-translation.csv` file in the `data-raw` folder.
* Create a new column for your language, with the column header being the language code.
* Create a pull request for your new language (make sure you follow the guidelines in `vignette("pull-request-guidelines")`).

### Improve an existing language

If you notice gaps in one of the existing languages, you can help us improve the package by expanding the dictionary for this language - especially in terms of data science-related words.

To fill the gaps for an existing language, follow these steps:

* Rollow the steps in the `vignette("getting-started")` guide (under **To contribute**) to fork, clone and install the package.
* Locate the `ui-translation.csv` file in the `data-raw` folder.
* Locate the column with the code of the language you're looking to improve and fill the gaps.
* Create a pull request for your language improvements (make sure you follow the guidelines in `vignette("pull-request-guidelines")`).

## Bugs

### How to report an issue

If you come across any issues in `shi18ny` we would appreciate if you could report them in the [issue section](https://github.com/datasketch/shi18ny/issues) of the package GitHub page.

If you are reporting an issue, please tell us:

* Which operating system you're using and its version.
* Detailed information about the issue.
* A minimal code example to reproduce the issue.

### How to fix an issue

You can help us out by fixing any of the open issues that have been filed in the [issue section](https://github.com/datasketch/shi18ny/issues) of the package GitHub page.

To fix an issue, follow these steps: 

* Follow the steps in the [Getting started]`vignette("getting-started")` guide (under **To contribute**) to fork, clone and install the package.
* Create a local branch from the master branch, with a branch name such as `fix/name_of_issue`.
* Fix the issue.
* Create a unit test for the issue you have fixed.
* Run all tests in the package to ensure no other issues have appeared (if you're using RStudio press Cmd/Ctrl + Shift T, otherwise run `devtools::test()`.
* Create a pull request for your issue fix (make sure you follow the guidelines in `vignette("pull-request-guidelines")`).

## New features

### Log feature request

We're always looking to expand `shi18ny` with new features that will promote the internationalisation of data science. If you have ideas for such features, don't hesitate to tell us by filing an issue on our GitHub page, and choose the issue type 'Feature request'.

### Implement features

To help us in advancing the internationalization of data science you can also implement your own feature (or implement one of the open feature requests in the [issue section](https://github.com/datasketch/shi18ny/issues) of the package GitHub page).

To implement your own feature, follow these steps: 

* Follow the steps in the `vignette("getting-started")` guide (under **To contribute**) to fork, clone and install the package.
* Create a local branch from the master branch, with a branch name such as `feature/name_of_feature`.
* Implement the feature.
* Create a unit test for the feature you have created.
* Run all tests in the package to ensure no issues have appeared (if you're using RStudio press Cmd/Ctrl + Shift T, otherwise run `devtools::test()`).
* Create a pull request for your feature with a description of the functionality of your feature (make sure you follow the guidelines in `vignette("pull-request-guidelines")`).

## Documentation

There is always scope for improving the `shi18ny` documentation. Helpful ways to contribute to the documentation could be

* Improving documentation of functionality and examples of individual functions.
* Adding to the range of examples on the package website.
* Adding articles about use cases to the package website.

**...thank you for your contributions!**

